INSERT INTO PUBLIC.BOARD (BOARD_TITLE, BOARD_CONTENT) VALUES ('test', 'test');
INSERT INTO PUBLIC.BOARD (BOARD_TITLE, BOARD_CONTENT) VALUES ('test2', 'test2');
INSERT INTO PUBLIC.COMMENT (BOARD_ID, WRITER, CONTENT) VALUES (1, 'seungdols', 'test ');
INSERT INTO PUBLIC.COMMENT (BOARD_ID, WRITER, CONTENT) VALUES (1, 'seungdols company', 'seungdols');
INSERT INTO PUBLIC.COMMENT (BOARD_ID, WRITER, CONTENT) VALUES (2, 'ten', '10');
INSERT INTO PUBLIC.COMMENT (BOARD_ID, WRITER, CONTENT) VALUES (2, 'any', '20');
